"""empty message

Revision ID: 0166876f74c0
Revises: a3d9abdaf0a3
Create Date: 2022-01-13 07:08:37.556758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0166876f74c0'
down_revision = 'a3d9abdaf0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_translation',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale')
    )
    op.drop_column('post', 'content')
    op.drop_column('post', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('post_translation')
    # ### end Alembic commands ###
