"""empty message

Revision ID: 93897dc2e154
Revises: c7f4382d1610
Create Date: 2022-04-25 22:59:21.800519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93897dc2e154'
down_revision = 'c7f4382d1610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'picture')
    # ### end Alembic commands ###
