"""empty message

Revision ID: 93bdd05c523d
Revises: ea1d29d05935
Create Date: 2022-01-08 14:45:57.394798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bdd05c523d'
down_revision = 'ea1d29d05935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_column('post', 'user_id')
    op.drop_column('post', 'timestamp')
    # ### end Alembic commands ###
