"""empty message

Revision ID: a3d9abdaf0a3
Revises: 1446647f0d81
Create Date: 2022-01-13 06:46:44.193491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d9abdaf0a3'
down_revision = '1446647f0d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'human_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'human_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
