"""empty message

Revision ID: a5471b0825f5
Revises: 0166876f74c0
Create Date: 2022-01-13 07:48:07.903891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5471b0825f5'
down_revision = '0166876f74c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_human_url_key', 'post', type_='unique')
    op.drop_column('post', 'human_url')
    op.add_column('post_translation', sa.Column('human_url', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'post_translation', ['human_url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_translation', type_='unique')
    op.drop_column('post_translation', 'human_url')
    op.add_column('post', sa.Column('human_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('post_human_url_key', 'post', ['human_url'])
    # ### end Alembic commands ###
