"""empty message

Revision ID: fd3c6b3901c1
Revises: 7f56a321e354
Create Date: 2022-01-13 06:37:40.835857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3c6b3901c1'
down_revision = '7f56a321e354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('human_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'human_url')
    # ### end Alembic commands ###
